"""empty message

Revision ID: 50763e037be8
Revises: 1d626f4dc4ee
Create Date: 2018-04-11 19:50:12.169064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50763e037be8'
down_revision = '1d626f4dc4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'created_time')
    # ### end Alembic commands ###
