"""empty message

Revision ID: 73313c28eb89
Revises: 4437b60b1490
Create Date: 2018-04-12 03:10:31.966553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73313c28eb89'
down_revision = '4437b60b1490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'created_time')
    # ### end Alembic commands ###
